language: ruby 
install:
- bundle install
script: bundle exec rake site:deploy
sudo: false
env:
  global:
    secure: wUNPjyTZeje73tVM4Fx9T6CZdX9YcESG4qcZSW6oLlCLaVEGM0ijwPoYaT1b13hApSEp/TvWTtREDTcK3CjlceeSlero22pNEw5nfz4XFN4w35wsCMoKtuX7G3vTBBaWrUxOo0fSq1ueff9d+IaTfjUu/iUqRwYEeDMJucRTuGGSUPgSaXTPAiEHGCWOpRB2S3iD+Unv2H5aNkuZuO451ww/5k13G1DGAmQE/4GVXJ2o7jNnsoywuGXnPPUO3r4Z2FDgrvdQfVNi/aEf4k3ygThCmAlzWCX7fz/2oM9XzQPct2e39stCD5TeFu6IXEH1/toTVeCsUlQn+IzmNVVSJOgvGi7SPVr/WnPRIwNJpZJPovZYgn9TmWOuuO2+kxUd2fa3Uaq/LRlERMudOia6gA/XDW9xjcVvpp6WV4jKL77Fp48WnFaxF44NsHB0kwsTeT8O6rVEV5Il76cS2thl3FrGAMmfJxi3X/2AbMcugMAs/v5bEHOdC8pyycn/AoBvS+rTB59kSYEVKuRefpo3yIrKchZs1JBhZzoMTj2BvHhlTxJKP4+6vHF07FJRO2yvwj0ockq3siuwpVxFFcqDLGlQbA6NVl1IXjxIEP0qKsyB6cA8KG2DhHNFgRDWjex4zFA1/HRsxel+VBL9OLz6qAGyEAbbkbKoHyXmT1lJnKA=
