{
  "formatVersion": "1.1",
  "component": {
    "group": "de.dfki.mary",
    "module": "emotionml-checker-java",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "emotionml-checker-java-1.2.2.jar",
          "url": "emotionml-checker-java-1.2.2.jar",
          "size": 20546,
          "sha512": "523b8bd02296c4394318058754c04fc425c481d8832e9f54806c645c625bfa385c0f61278f8d946f2d41dd4a1b6c8911091246be9b8d39522463d8d270302777",
          "sha256": "585757b3dee5d84b120140aadc02cde8fe0692f1253180605cdacf12e6125d2c",
          "sha1": "dcb9d1f789ec362bbfb3b45e61463951915b7b64",
          "md5": "a4b667f9415539b1668de1a1f820146c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emotionml-checker-java-1.2.2.jar",
          "url": "emotionml-checker-java-1.2.2.jar",
          "size": 20546,
          "sha512": "523b8bd02296c4394318058754c04fc425c481d8832e9f54806c645c625bfa385c0f61278f8d946f2d41dd4a1b6c8911091246be9b8d39522463d8d270302777",
          "sha256": "585757b3dee5d84b120140aadc02cde8fe0692f1253180605cdacf12e6125d2c",
          "sha1": "dcb9d1f789ec362bbfb3b45e61463951915b7b64",
          "md5": "a4b667f9415539b1668de1a1f820146c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emotionml-checker-java-1.2.2-sources.jar",
          "url": "emotionml-checker-java-1.2.2-sources.jar",
          "size": 12497,
          "sha512": "3f911319e6f4128e13688b4417ebb056bc996ab7e24b7aa0c7161a8b67876426557a78212b5fb170724d785b02f0043f4605ec90b52e837898135a0bd44e6d96",
          "sha256": "f0a85cf113c6ad37c0ad7308648c134ca717bf5480c7ac2b013ffae1d9895db6",
          "sha1": "b13ecad2e8c0a92da298ffc14fc78dce7eb101d3",
          "md5": "89928cf129ad7b6e058d8cc78c0ef3ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emotionml-checker-java-1.2.2-javadoc.jar",
          "url": "emotionml-checker-java-1.2.2-javadoc.jar",
          "size": 50124,
          "sha512": "16e4983610500574ccbd4e9fe09f05bfd7332d482dcbe066bd7c75d63b8840e756d6a93155f854335e500fc118f027e10b4d0a613cb64adcb62de88c5f86789a",
          "sha256": "b527045dbee99c4900820e10493c4297266f6e666927682f2e18ecb401c2105e",
          "sha1": "1835025d4f2df2ef5b33d53a2d48b2baaebab069",
          "md5": "b009cc60b9a3a73768b8bbe076e43691"
        }
      ]
    }
  ]
}
